name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: package.json
        cache: npm
    - name: Setup Firebase CLI
      uses: w9jds/setup-firebase@d855fa20e1b50e7d53d8b0d283186f98db963f36
      with:
        tools-version: 11.16.1
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}
    - name: Install dependencies
      run: npm ci
    - name: Deploy Firebase functions
      run: |
        firebase use sejuega-telegram-bot
        firebase functions:config:set telegram.token="${{ secrets.TELEGRAM_BOT_TOKEN }}"
        firebase deploy --only functions
        echo TELEGRAM_BOT_WEBHOOK_URL=$(firebase functions:list --json | jq -r '.result[0].uri') >> $GITHUB_ENV
    - name: Update Telegram bot webhook URL
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_BOT_WEBHOOK_URL: ${{ env.TELEGRAM_BOT_WEBHOOK_URL }}
      run: curl -vv -X GET "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/setWebhook?url=$TELEGRAM_BOT_WEBHOOK_URL/${{ env.TELEGRAM_BOT_TOKEN }}"
